# Generated by Django 4.1.6 on 2023-02-10 04:59

import Osi.models
import Osi.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsAgeIntervalBorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_border_value', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('upper_border_value', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=Osi.models.fields_file_path, validators=[Osi.validators.validate_file_size])),
                ('numerator_params_quantity', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)])),
                ('denominator_params_quantity', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(15)])),
                ('divide_by_age', models.BooleanField(default=False)),
                ('divide_by_gender', models.BooleanField(default=False)),
                ('divide_by_ethnicity', models.BooleanField(default=False)),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsDivideByEthnicityDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divide_by_ethnicity', models.IntegerField(default=0)),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsDivisionCols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_col', models.CharField(default='', max_length=30)),
                ('gender_col', models.CharField(default='', max_length=30)),
                ('ethnicity_col', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('data_columns', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsExcelFileDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_default', models.FileField(upload_to=Osi.models.fields_default_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(default=0)),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsPatientDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default='')),
                ('age', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('ethnicity', models.CharField(default='', max_length=40)),
                ('dk', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('kd_st', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('mda', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('cod', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('gsh', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('e', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('a', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('ethnicity_values', models.CharField(default='', max_length=10000)),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsPatientDenParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('value', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('norm', models.CharField(default='', max_length=60)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('data_columns', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsPatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default='')),
                ('age', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('gender', models.CharField(default='', max_length=20)),
                ('ethnicity', models.CharField(default='', max_length=40)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('gender_values', models.CharField(default='', max_length=10000)),
                ('ethnicity_values', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsPatientNumParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('value', models.FloatField(default='', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)])),
                ('norm', models.CharField(default='', max_length=60)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('data_columns', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsPatientResultExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_excel_file', models.FileField(upload_to='')),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsPatientTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_table', models.CharField(default='', max_length=3000)),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsSelectionCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_col', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('data_columns', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FieldsSelectionColValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_selection_value', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('selection_col_values', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='FileAgeIntervalBorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_border_value', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('upper_border_value', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileAgeIntervalsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervals_quantity', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=Osi.models.file_file_path, validators=[Osi.validators.validate_file_size])),
                ('numerator_params_quantity', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)])),
                ('denominator_params_quantity', models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(15)])),
                ('divide_by_age', models.BooleanField(default=False)),
                ('divide_by_gender', models.BooleanField(default=False)),
                ('divide_by_ethnicity', models.BooleanField(default=False)),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileDenominatorParamCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den_param_col', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('data_columns', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FileDivisionCols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_col', models.CharField(default='', max_length=30)),
                ('gender_col', models.CharField(default='', max_length=30)),
                ('ethnicity_col', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('data_columns', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FileEthnicityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity_value', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('ethnicity_values', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='FileEthnicityValuesQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity_values_quantity', models.IntegerField(default='')),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('unique_values_quantity', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FileGenderValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_value', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('gender_values', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='FileGenderValuesQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_values_quantity', models.IntegerField(default='')),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileIdCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_col', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('data_columns', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FileNumeratorParamCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_param_col', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('data_columns', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FileOsiResultsArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osi_results_archive', models.FileField(upload_to='')),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileOsiResultsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osi_results_file', models.FileField(upload_to='')),
                ('user_session_key', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileSelectionCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_col', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('data_columns', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='FileSelectionColValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_selection_value', models.CharField(default='', max_length=30)),
                ('case_selection_value', models.CharField(default='', max_length=30)),
                ('user_session_key', models.CharField(default='', max_length=100)),
                ('selection_col_values', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
