# Generated by Django 4.1.3 on 2023-01-17 09:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doctor', models.CharField(max_length=200, verbose_name='Имя доктора')),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ethnicity', models.CharField(max_length=50, verbose_name='Наименование ethnicity')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('day_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('card_number', models.CharField(max_length=20, verbose_name='Номер карты')),
                ('barcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Штрих-код')),
                ('sex', models.CharField(choices=[('1', 'Мужской'), ('2', 'Женский')], default='2', max_length=15)),
                ('place_of_birth', models.CharField(blank=True, max_length=20, null=True, verbose_name='Место рождения')),
                ('urban_rural', models.CharField(blank=True, choices=[('1', 'Город'), ('2', 'Сельская местность')], default='1', max_length=15, null=True)),
                ('day_of_begin', models.DateField(verbose_name='Дата начала диспансерного наблюдения')),
                ('ethnicity_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Pcos.ethnicity')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('age_visit', models.PositiveIntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('SBP', models.PositiveIntegerField(blank=True, null=True)),
                ('DBP', models.PositiveIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('inform_consent', models.BooleanField(default=True)),
                ('comply_all_study', models.BooleanField(default=True)),
                ('female_age', models.BooleanField(default=True)),
                ('current_preg_lact', models.BooleanField(default=False)),
                ('history_hysterectomy', models.BooleanField(default=False)),
                ('risk_no_compliance', models.BooleanField(default=False)),
                ('unwillingness', models.BooleanField(default=False)),
                ('medicince_listed_now_10', models.BooleanField(default=True)),
                ('medicince_listed_3month_10', models.BooleanField(default=True)),
                ('pnya', models.BooleanField(default=False)),
                ('PCOS', models.IntegerField(blank=True, null=True)),
                ('Exclusion', models.IntegerField(blank=True, null=True)),
                ('Grey', models.IntegerField(blank=True, null=True)),
                ('Phenotype', models.CharField(blank=True, max_length=1, verbose_name='Фенотип')),
                ('PCOS_text', models.TextField(blank=True, max_length=500, verbose_name='Заключение')),
                ('Exclusion_text', models.TextField(blank=True, max_length=500, verbose_name='Причины исключения')),
                ('doctor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.doctor')),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ultrasound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_ovary_key', models.CharField(choices=[('1', 'Визуализируется'), ('2', 'Не визуализируется'), ('3', 'Отсутствует')], default='1', max_length=15)),
                ('right_ovary_key', models.CharField(choices=[('1', 'Визуализируется'), ('2', 'Не визуализируется'), ('3', 'Отсутствует')], default='1', max_length=15)),
                ('date', models.DateField()),
                ('right_volume_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('right_follicle_total', models.PositiveIntegerField(blank=True, null=True)),
                ('diameter_right_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('left_volume_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('left_follicle_total', models.PositiveIntegerField(blank=True, null=True)),
                ('diameter_left_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('left_ovary_front', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('right_ovary_front', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('left_ovary_posterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('right_ovary_posterior', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('left_ovary_side', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('right_ovary_side', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('doctor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.doctor')),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.patient')),
                ('visit_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_mens_prl', models.PositiveIntegerField()),
                ('value_testosteron', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_shbg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_dheas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_tsh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_17hp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_prl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_testosteron_max', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_IFA_max', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_dheas_max', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_tsh_min', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_tsh_max', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_17hp_max_1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_prl_max_1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('value_prl_max_2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.patient')),
                ('visit_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('periods', models.CharField(choices=[('1', 'Регулярный'), ('2', 'Нерегулярный'), ('3', 'Отсутствует')], default='1', max_length=15)),
                ('type_menstrual_disorders_1', models.CharField(choices=[('1', 'Аменорея отсутствует'), ('2', 'Первичная аменорея'), ('3', 'Вторичная аменорея')], default='1', max_length=25)),
                ('type_menstrual_disorders_3', models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default='No')),
                ('type_menstrual_disorders_4', models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default='No')),
                ('min_menstrual', models.PositiveIntegerField()),
                ('max_menstrual', models.PositiveIntegerField()),
                ('sum_physician', models.PositiveIntegerField()),
                ('hirsutism', models.CharField(blank=True, choices=[('1', 'Нет'), ('2', 'Есть')], default='1', max_length=25, null=True)),
                ('doctor_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.doctor')),
                ('patient_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.patient')),
                ('visit_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pcos.visit')),
            ],
        ),
    ]
